USE [master]
GO

/****** Object:  Database [ChallengeDB]    Script Date: 18/2/2021 20:47:51 ******/
CREATE DATABASE [ChallengeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ChallengeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ChallengeDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ChallengeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ChallengeDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ChallengeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ChallengeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ChallengeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ChallengeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ChallengeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ChallengeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ChallengeDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ChallengeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ChallengeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ChallengeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ChallengeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ChallengeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ChallengeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ChallengeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ChallengeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ChallengeDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ChallengeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ChallengeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ChallengeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ChallengeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ChallengeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ChallengeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ChallengeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ChallengeDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ChallengeDB] SET  MULTI_USER 
GO

ALTER DATABASE [ChallengeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ChallengeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ChallengeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ChallengeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ChallengeDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ChallengeDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ChallengeDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ChallengeDB] SET  READ_WRITE 
GO


CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Apellido] [varchar](50) NULL,
	[Email] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL
) ON [PRIMARY]
GO


INSERT INTO [User]
VALUES
(
	'Fernando',
	'Herrera',
	N'fernandoh887@gmail.com',
	N'challenge123'
),
(
	'Javier',
	'Demitropulos',
	N'fernando_8_87@hotmail.com',
	N'challenge234'
),
(
	'Sandra',
	'San Juan',
	N'sandra_sanjuan@gmail.com',
	N'challenge345'
),
(
	'Victoria',
	'San Juan',
	N'victoria_sanjuan@gmail.com',
	N'challenge456'
)

GO

CREATE TABLE [dbo].[Conversion](
	[ID] [int] IDENTITY(1,1) PRIMARY KEY,
	[CurrencyBase] [nvarchar](3) NOT NULL,
	[CurrencyQuote] [nvarchar](3) NOT NULL,
	[Ratio] [decimal](18, 8) NULL,
	[InvRate] [decimal](18, 8) NULL,
	[CreationDate] [date] NULL,
	[ValidUntil] [date] NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CurrencyHistory](
	[ID] [int] IDENTITY(1,1) PRIMARY KEY,
	[CurrencyId] [varchar](3) NOT NULL,
	[Symbol] [nvarchar](4) NULL,
	[Description] [varchar](50) NULL,
	[DecimalPlaces] [int] NULL,
	[ToDolar] [int] FOREIGN KEY REFERENCES Conversion(ID)
)
GO
